### ISSUE TITLE
Add a placeholder for issue title, ex. [BUG]

### ISSUE THREAD

**Issue by CyberDudeJ** [Supernova3339/SuperPad#4]
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
Add extensions that users can install like a toolbar like ms word, etc

**Describe alternatives you've considered**
nothing.

this is very serious

**Comment by Supernova3339** [comment]
We've added a website instead. Issue closed. 
If you want extensions, implement them yourself.
